# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/tg_sender/tg_sender.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsrc/tg_sender/tg_sender.proto\x12\ttg_sender\"u\n\x0eMessageOptions\x12\x12\n\nparse_mode\x18\x01 \x01(\t\x12\x1b\n\x13\x65scape_for_markdown\x18\x02 \x01(\x08\x12 \n\x18\x64isable_web_page_preview\x18\x03 \x01(\x08\x12\x10\n\x08reply_to\x18\x04 \x01(\x03\"U\n\x08SentText\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\t\x12*\n\x07options\x18\x03 \x01(\x0b\x32\x19.tg_sender.MessageOptions\"g\n\tSendPhoto\x12\x0f\n\x07\x63\x61ption\x18\x01 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\t\x12\x0c\n\x04path\x18\x03 \x01(\t\x12*\n\x07options\x18\x04 \x01(\x0b\x32\x19.tg_sender.MessageOptions\"i\n\nSendPhotos\x12\x0f\n\x07\x63\x61ption\x18\x01 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\t\x12\r\n\x05paths\x18\x03 \x03(\t\x12*\n\x07options\x18\x04 \x01(\x0b\x32\x19.tg_sender.MessageOptionsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.tg_sender.tg_sender_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGEOPTIONS._serialized_start=44
  _MESSAGEOPTIONS._serialized_end=161
  _SENTTEXT._serialized_start=163
  _SENTTEXT._serialized_end=248
  _SENDPHOTO._serialized_start=250
  _SENDPHOTO._serialized_end=353
  _SENDPHOTOS._serialized_start=355
  _SENDPHOTOS._serialized_end=460
# @@protoc_insertion_point(module_scope)
