# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: tg_sender.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class MessageOptions(betterproto.Message):
    parse_mode: str = betterproto.string_field(1)
    enable_web_page_preview: bool = betterproto.bool_field(3)
    reply_to: int = betterproto.int64_field(4)


@dataclass
class MessageDetails(betterproto.Message):
    in_process: bool = betterproto.bool_field(1)
    sent: bool = betterproto.bool_field(2)
    message_id: int = betterproto.int64_field(3)


@dataclass
class SendText(betterproto.Message):
    text: str = betterproto.string_field(1)


@dataclass
class SendPhoto(betterproto.Message):
    caption: str = betterproto.string_field(1)
    path: str = betterproto.string_field(2)


@dataclass
class SendPhotos(betterproto.Message):
    caption: str = betterproto.string_field(1)
    paths: List[str] = betterproto.string_field(2)


@dataclass
class SendFile(betterproto.Message):
    caption: str = betterproto.string_field(1)
    path: str = betterproto.string_field(2)


@dataclass
class Forward(betterproto.Message):
    from_channel: str = betterproto.string_field(1)
    message_id: int = betterproto.int64_field(2)


@dataclass
class Pin(betterproto.Message):
    message_id: int = betterproto.int64_field(1)
    enable_notification: bool = betterproto.bool_field(2)


@dataclass
class Unpin(betterproto.Message):
    message_id: int = betterproto.int64_field(1)


@dataclass
class TaskDetails(betterproto.Message):
    in_process: bool = betterproto.bool_field(1)
    sent: bool = betterproto.bool_field(2)
    result: int = betterproto.int64_field(3)


@dataclass
class Delete(betterproto.Message):
    message_id: int = betterproto.int64_field(1)


@dataclass
class Button(betterproto.Message):
    text: str = betterproto.string_field(1)
    callback_data: str = betterproto.string_field(2)


@dataclass
class SendMarkup(betterproto.Message):
    text: str = betterproto.string_field(1)
    buttons: List["Button"] = betterproto.message_field(2)


@dataclass
class Task(betterproto.Message):
    options: "MessageOptions" = betterproto.message_field(1)
    details: "TaskDetails" = betterproto.message_field(2)
    channel: str = betterproto.string_field(3)
    thread_id: int = betterproto.int64_field(4)
    custom_int_field: int = betterproto.int64_field(5)
    custom_string_field: str = betterproto.string_field(6)
    send_text: "SendText" = betterproto.message_field(7, group="task")
    send_photo: "SendPhoto" = betterproto.message_field(8, group="task")
    send_photos: "SendPhotos" = betterproto.message_field(9, group="task")
    send_file: "SendFile" = betterproto.message_field(10, group="task")
    forward: "Forward" = betterproto.message_field(11, group="task")
    pin: "Pin" = betterproto.message_field(12, group="task")
    unpin: "Unpin" = betterproto.message_field(13, group="task")
    delete: "Delete" = betterproto.message_field(14, group="task")
    send_markup: "SendMarkup" = betterproto.message_field(15, group="task")
